### ISSUE TITLE
Modifying env variables while running.

### ISSUE THREAD

**Issue by FrozenDude101** [CSSUoB/TeX-Bot-Py-V2#45] opened 2023-09-16 14:46 UTC
Certain env variables might be nice to be able to change while the bot is running.
Things like if strikes actions should be performed automatically, or reminders to join the server could be easily toggled.

Obviously things like the discord token and things set on startup can be set to not be able to change.

I don't know if it could set these in whatever runs the bot, so if it has to restart for some reason, the new settings are saved.

**Comment by CarrotManMatt** [comment] 2023-11-25 23:36
It would also be useful for some required variables to allow empty values when a new variable `DEBUG` is set to `True`. This `DEBUG` variable should be `False` by default, and passed through to the Django `DEBUG` variable

**Comment by CarrotManMatt** [comment] 2024-05-03 15:08
This will be completed in tandem with #165

**Comment by MattyTheHacker** [comment] 2024-05-04 22:02
dupe of #165

**Closed** 2024-05-04 22:02 UTC
Labels: duplicate
